name: test-coverage-manuel
on: workflow_dispatch
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '14'
    - run: npm install -g yarn
    - run: yarn install
    - uses: paambaati/codeclimate-action@v2.7.2
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: yarn run test:coverage
        debug: true
